# Generated by Django 2.0.5 on 2020-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201230_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='downloads'),
        ),
        migrations.AddField(
            model_name='user',
            name='tclass',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
